### PR TITLE
added support for event

### PR DESCRIPTION
**Pull request by slince**

### CODE REVIEW

**Comment by ADmad** [comment]
Hmm.. Using EventDispatcherTrait means a new event manager instance will be created for the middleware. I would rather just use the global event manager. Also don't really like the extra event classes. I prefer keeping things simple.

Let me think about this and see if I can come up with a simpler way to use event system to deal with exceptions.

**Comment by slince** [comment]
@ADmad  

> Using EventDispatcherTrait means a new event manager instance will be created

I know what you mean. we can use global  eventmanager in `GlideMiddleware` constructor to avoid creating multi instance. I have committed for this.

> Also don't really like the extra event classes. 
This is  not important, event class was designed to be extended.

**Comment by ADmad** [comment]
@slince I have PR #20 ready for new version of plugin using Cake 3.5 which triggers event in case of exception (along with few other changes).

**Comment by slince** [comment]
@ADmad   That sounds great.  Look forward to the next release

**Pull request closed without merging**
